### ISSUE TITLE
Refactor To Gatsby.js

### ISSUE THREAD

**Issue by MykalMachon** [ufvcsa/ufvcsa.github.io#12]
I had a brief conversation with @MJJBennett over discord about moving the site over to a static site generator, more specifcally, [Gatsby.js](https://www.gatsbyjs.org/). 

He mentioned I should make an issue to track progress and to facilitate conversation about this move.

### Benefits of Gatsby over plain HTML, CSS, and JS
Here's a quick list of why I think Gatsby would be a good fit for this project
1. **Static Content  :** Gatsby enables you to import the data for your pages from anywhere, including static files in the repository! Whenever these files are changed, or created through a commit Gatsby automatically rebuilds the site. This would make adding new pages to the website as easy as committing a markdown file to the repo! 
2.  **Modern Workflow :** Gatsby.js uses modern, real-world technologies like NPM, React.js, and Node.js; all tools that are in high demand in the workplace. By exposing CSA memebers to these tools through this repo, we can better prepare students for the workforce!
3. **Opportunities for Everyone :** While Gatsby is not neccesarily a framework for beginners, due to the large range of technologies used, it creates opportunities for CSA members of all skill levels to contribute. 
4. **Lots more :** If you're interested in learning more about the benefits, you can check out their site [here](https://gatsbyjs.org)

### Action Items
If we decided that this is something we're looking to go forward with, there are a few things that we'll have to do get started

- [x] **Transfer existing site over to Gatsby.js** ➡️ 
     - [x] Create a gatsby project 🎉 
     - [x] Move sitewide elements into components (Header, Footer, Navbar) 📦 
     - [x] Create Markdown pages for each page 📄 
     - [x] Generate all site pages based on markdown files ⚙️ 
- [x] **Write beginner friendly documentation** 📖 
     - [x] Create a quick-start with gatsby for beginners (how to develop locally, basic explanation of concepts, etc) 📚 
     - [x] Update contribution docs to reflect the gatsby setup 🔧 
- [x]  **Determine if we need to update hosting** (Gatsby works best when it's automatically rebuilt upon commits to the master branch. There are lots of great free hosting options that provide this, I would reccommend [Netlify ](https://www.netlify.com/) or [Now](https://zeit.co/) if it's needed) 

### General Notes & Discussion
Since this is a relatively large change to the repo, I'd love to talk about what other contributors think! If you're interested in helping out, have any questions about gatsby, or think this isn't the best way to go forward I'd love to discuss it below!

Thanks for your time 😄 
I'm looking forward to working on the project in any capacity 💯

**Comment by MJJBennett** [comment]
CC @codybeaty

**Comment by MJJBennett** [comment]
This sounds good, as far as I'm aware nobody else is working on this currently. :+1: 

Feel free to create sub-issues that link back to this one for the subdivided tasks. I'll read up on Gatsby this week so you're not alone.

**Comment by MykalMachon** [comment]
Awesome! Will do :+1: 
I'll probably break this down into three issues (one for each heading in the action items list)

**Comment by MykalMachon** [comment]
See #19 for information on hosting changes!
We're officialy on Gatsby!
