### ISSUE TITLE
Epic: Move To Astro

### ISSUE THREAD

**Issue by MykalMachon** [ufvcsa/ufvcsa.github.io#49]
## Summary of Issue
We should move the CSA website from Gatsby to Astro. 
This is for a number of reasons: 
1. Astro doesn't require you to know react/preact/svelte/vue, you just need to know HTML, CSS, and JS. It's more approachable
2. Astro is a lot more lightweight than Gatsby and enables us to do quite a bit more with much less code/complexity
3. By making the initial barrier to entry lower, and the maintenance cost lower, the CSA website should be much friendlier to knew contributors 

## Action Items
- [ ] Initial Move to Astro: just setup a new Astro site with the basics
- [ ] Implement Basic Homepage: with placeholder content
- [ ] Implement Blog: Implement a basic template for a "blog" type page (list components, pages, etc)
- [ ] more to come
